// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbfpenyrufqnnotiypcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiZnBlbnlydWZxbm5vdGl5cGNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MDQ1MTMsImV4cCI6MjA3Mjk4MDUxM30.v1pCIoDBoet1XikcYvTqrEzxhEvYbLvyrGXSZ6S7Y-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});